services:
  - type: web
    name: cwrv-predictor
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
